defaults:
  - task: mw
  - system: autoencoder
  - _self_

device:
  cuda_visible_devices:  "0,1,2,3,4,5,6"
  id: 1
  cuda: cuda:${device.id}

load_system_checkpoint:
mode: train

seed: 42
process_title: p-diff

output_dir: outputs/mw

hydra:
  output_subdir: config
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.override_dirname}